

import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Enri
 */
public class ventana extends javax.swing.JFrame {

   

    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox = new javax.swing.JComboBox<>();
        txtNuevoElemento = new javax.swing.JTextField();
        botonAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonAñadirTodos = new javax.swing.JButton();
        botonBorrarTodos = new javax.swing.JButton();
        comboboxGrado = new javax.swing.JComboBox<>();
        botonTrash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar elementos combox");
        setResizable(false);

        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Añade el nombre de los modulos que estes matriculado :");

        botonAñadirTodos.setText("Añadir todos");
        botonAñadirTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirTodosActionPerformed(evt);
            }
        });

        botonBorrarTodos.setText("Borrar todos");
        botonBorrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodosActionPerformed(evt);
            }
        });

        comboboxGrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primero", "Segundo" }));

        botonTrash.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enri\\Documents\\GitHub\\pr-ctica-2-3-elementos-combobox-Enrique504\\media\\trash.png")); // NOI18N
        botonTrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBorrarTodos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(botonAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAñadirTodos)))
                .addGap(218, 218, 218))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(botonTrash))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(comboboxGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboboxGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(combobox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNuevoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonTrash))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAñadir)
                    .addComponent(botonAñadirTodos))
                .addGap(18, 18, 18)
                .addComponent(botonBorrarTodos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        // TODO add your handling code here:
        String nuevoElemento = txtNuevoElemento.getText(); 
        
        if(nuevoElemento.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "No puedes añadir un campo vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean existe = false;
        for (int i = 0; i < combobox.getItemCount(); i++) {
            if (combobox.getItemAt(i).equalsIgnoreCase(nuevoElemento)) {
                existe = true;
                break;

            }
        }

        if (existe) {
            
            JOptionPane.showMessageDialog(this, "El elemento ya existe en el ComboBox.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
          
            combobox.addItem(nuevoElemento);
           
        }

        // Limpiar el campo de texto después de añadir
        txtNuevoElemento.setText("");
    }//GEN-LAST:event_botonAñadirActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void botonAñadirTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirTodosActionPerformed
        // TODO add your handling code here:
        String primero[] = {"fol", "sistemas", "bases de datos", "programacion", "entornos", "marcas"};
        String segundo[] = {"datos", "interfaces", "servicios y procesos", "sistemas", "empresa", "dispositivos mòviles"};
        
        if (comboboxGrado.getSelectedItem().toString().equalsIgnoreCase("primero")) {
            if (combobox.getItemCount() < 6) {
                for (int i = 0; i < primero.length; i++) {

                    combobox.addItem(primero[i]);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se puede volver añadir los mismo cursos", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
        
        if (comboboxGrado.getSelectedItem().toString().equalsIgnoreCase("segundo")) {
            if (combobox.getItemCount() < 6) {
                for (int i = 0; i < segundo.length; i++) {

                    combobox.addItem(segundo[i]);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No se puede volver añadir los mismo cursos", "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
        
    
        
        
        
    }//GEN-LAST:event_botonAñadirTodosActionPerformed

    private void botonBorrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodosActionPerformed
        // TODO add your handling code here:
        combobox.removeAllItems();
        
    }//GEN-LAST:event_botonBorrarTodosActionPerformed

    private void botonTrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrashActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < combobox.getItemCount(); i++) {
            if (i == combobox.getSelectedIndex()) {
                combobox.removeItemAt(i);
            }
        }
    }//GEN-LAST:event_botonTrashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonAñadirTodos;
    private javax.swing.JButton botonBorrarTodos;
    private javax.swing.JButton botonTrash;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JComboBox<String> comboboxGrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNuevoElemento;
    // End of variables declaration//GEN-END:variables

    }
